---
version: '3'
services:
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    networks:
      - docker.local
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - docker.local
    ports:
      - 9411:9411

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - docker.local
    depends_on:
      - zookeeper
    #        - zipkin
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  zoonavigator:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator
    depends_on:
      - zookeeper
    networks:
      - docker.local
    ports:
      - 9000:9000


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - docker.local
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - docker.local
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

networks:
  docker.local:
    external: true
