

server:
    port: 8540
    error:
        whitelabel:
            enabled: false
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"
spring:
    application:
        name: sample-api
    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:sampledb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        hikari:
            pool-name: h2-hikari
            maximum-pool-size: 10
            minimum-idle: 2
            connection-timeout: 20000
            idle-timeout: 30000
            max-lifetime: 2000000
            leak-detection-threshold: 20000
            validation-timeout: 5000
            test-while-idle: true
            validation-query: SELECT 1
        initialization-mode: never
    sql:
        init:
            mode: always
            platform: h2
            continue-on-error: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        open-in-view: false
        show-sql: true
        defer-datasource-initialization: true
        properties:
            hibernate:
                format_sql: true
                enable_lazy_load_no_trans: true
                jdbc:
                    lob:
                        non_contextual_creation: true
    h2:
        console:
            enabled: true
            path: /h2-console

    jackson:
        serialization:
            write-dates-as-timestamps: false
    mvc:
        favicon:
            enabled: false
        throw-exception-if-no-handler-found: true
