server:
    port: 8080
spring:
    activemq:
        broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=0
        password: admin
        user: admin
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
        username: sa
        password: ''
        jpa:
            hibernate:
                hbm2ddl:
                    auto: update
    h2:
        console:
            enabled: true
            path: /console
    properties:
        hibernate:
            format_sql: true
            id:
                new_generator_mappings: true
            show_sql: true

clients:
    endpoints:
        cep-client:
            url: http://localhost:8080
